name: bgo
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

isar_version: &isar_version 3.1.0 # define the version to be used

dependencies:
  bgg_api: ^0.8.0
  cached_network_image: ^3.3.1
  dio:
  easy_debounce: ^2.0.3
  fpdart:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.0
  path_provider:
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  isar_generator: *isar_version
  build_runner: any

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
